const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync('/home/gobotmini/code/choose-adventure/src/app/api/turn/route.ts', 'utf8');

assert.match(source, /encodeEvent\("meta"/);
assert.match(source, /encodeEvent\("chunk"/);
assert.match(source, /encodeEvent\("done"/);
assert.match(source, /persistTurn\(/);
assert.match(source, /suggestedChoices/);
assert.match(source, /characterUpdate/);
assert.match(source, /discoveries/);
assert.match(source, /locations/);
assert.match(source, /people/);
assert.match(source, /factions/);
assert.match(source, /routes/);
assert.match(source, /threats/);
assert.match(source, /facts/);
assert.match(source, /flattenDiscoveries/);
assert.match(source, /role/);
assert.match(source, /relationship/);
assert.match(source, /isCompanion/);
assert.match(source, /isActive/);
assert.match(source, /persistDiscovery/);
assert.match(source, /persistTeamMember/);
assert.match(source, /bodyState/);
assert.match(source, /mindState/);
assert.match(source, /conditions/);
assert.match(source, /collapsed/);
assert.match(source, /shaken/);
assert.match(source, /buildFullNarratorStatePayload/);
assert.match(source, /buildDeltaNarratorStatePayload/);
assert.match(source, /chooseNarratorContextMode/);
assert.match(source, /choosePromptMode/);
assert.match(source, /Session-start reminder/);
assert.match(source, /Prompt mode:/);
assert.match(source, /Context mode:/);
assert.match(source, /worldUpdate/);
assert.match(source, /ReadableStream/);
assert.match(source, /openrouter/i);
assert.match(source, /OPENROUTER_MODEL/);
assert.match(source, /DEFAULT_OPENROUTER_MODEL/);
assert.match(source, /getWriterModel/);

console.log('turn route integration checks passed');
